"""creating tables

Revision ID: c4231416f410
Revises: None
Create Date: 2016-05-27 13:33:52.482753

"""

# revision identifiers, used by Alembic.
revision = 'c4231416f410'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    ### end Alembic commands ###
